project_id = "fbzsjvifhhaumzjedvmj"

[functions.polar-webhook]
verify_jwt = false

[functions.polar-customer-portal]
verify_jwt = true

[functions.token-purchase]
verify_jwt = true

[functions.process-video]
verify_jwt = true