// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbzsjvifhhaumzjedvmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZienNqdmlmaGhhdW16amVkdm1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNTMwNDUsImV4cCI6MjA3MjYyOTA0NX0.rQgAu0UxgjEBsQvge65e08Or4VvpHafUKmPTke9FagU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});